### ISSUE TITLE
Migrating code from iris.experimental.raster

### ISSUE THREAD

**Issue by pelson** [SciTools-incubator/iris-raster#1]
As discussed in https://github.com/SciTools/iris/pull/2952#issuecomment-365549891

cc @cpelley.

It would be great to keep the git history of the key files.

**Comment by cpelley** [comment]
Thanks @pelson.
https://github.com/SciTools/iris/pull/2160 may require investigation.

**Comment by pelson** [comment]
Want to open an issue for it on here and we can track the specifics there?

**Comment by cpelley** [comment]
I have made the initial commit.  Are you happy with the default of a BSD license? (following from taking hint from python-stratify).

**Comment by pelson** [comment]
> Are you happy with the default of a BSD license? 

I don't think we can do that just yet - we need to be careful to ensure that contributors who have added to this codebase are OK with it (the CLA states that we will *not* relicense from LGPL without that express permission). There are some conversations ongoing around this subject.

Stick with the standard Iris license, and we will change it if/when we change Iris (I hope that is going to happen in the near future).

**Comment by cpelley** [comment]
OK thanks @pelson.  I'll change accordingly before I migrate the code.

+1 on iris moving to BSD :)  I wonder if the current license is acting as a barrier to usage...

**Comment by pelson** [comment]
@cpelley - do you have any plans to make this move? I'm keen to reduce the number of obsolete repos in SciTools, and this one hasn't gone anywhere yet. No worries if you do have plans, just don't want it sitting around needlessly.

**Comment by cpelley** [comment]
Thanks for the ping @pelson, I'll see what I can do.

**Comment by cpelley** [comment]
As per https://github.com/SciTools-incubator/iris-raster/pull/5#issuecomment-507713235, closing
